[package]
name = "peer_router"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = { version = "0.11", default-features = false, features = ["aes","rand_core"] }
ed25519-dalek = { version = "3", default-features = false }
rand_core = "0.6"
x25519-dalek = { version = "3", default-features = false, features = ["reusable_secrets", "zeroize"] }
