apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.14.5
    helm:
      values: |
        installCRDs: true
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: longhorn-selfsigned
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-selfsigned-cert
  namespace: default
spec:
  commonName: longhorn.hattmo.com
  dnsNames:
    - longhorn.hattmo.com
  secretName: longhorn-selfsigned-tls
  issuerRef:
    name: longhorn-selfsigned
    kind: ClusterIssuer
    group: cert-manager.io
