apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.11.2
      helm:
        values: |
          preUpgradeChecker:
            jobEnabled: false
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: longhorn-ui
  namespace: longhorn-system
spec:
  parentRefs:
    - name: private
      sectionName: https
      namespace: default
  hostnames:
    - longhorn.hattmo.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: longhorn-frontend
          namespace: longhorn-system
          port: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-selfsigned-cert
  namespace: default
spec:
  commonName: longhorn.hattmo.com
  dnsNames:
    - longhorn.hattmo.com
  secretName: longhorn-selfsigned-tls
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
    group: cert-manager.io
