apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  sources:
    - chart: traefik
      repoURL: https://traefik.github.io/charts
      targetRevision: v38.0.1
      helm:
        values: |
          ingressRoute:
            dashboard:
            enabled: true
            matchRule: Host(`dashboard.hattmo.com`)
            entryPoints:
              - web
          providers:
            kubernetesGateway:
              enabled: true
          gateway:
            listeners:
              web:
                namespacePolicy:
                  from: All
